In [ ]:
import pandas as pd

In [ ]:
# reviews = pd.read_csv('/content/Reviews.csv', encoding = 'latin1')

# reviews.info()

In [ ]:
listings =  pd.read_csv('/content/Listings.csv', encoding = 'latin1')

<ipython-input-3-b2795b18c5fa>:1: DtypeWarning: Columns (5,13) have mixed types. Specify dtype option on import or set low_memory=False.
  listings =  pd.read_csv('/content/Listings.csv', encoding = 'latin1')

In [ ]:
listings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 279712 entries, 0 to 279711
Data columns (total 33 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   listing_id                   279712 non-null  int64
 1   name                         279539 non-null  object
 2   host_id                      279712 non-null  int64
 3   host_since                   279547 non-null  object
 4   host_location                278872 non-null  object
 5   host_response_time           150930 non-null  object
 6   host_response_rate           150930 non-null  float64
 7   host_acceptance_rate         166625 non-null  float64
 8   host_is_superhost            279547 non-null  object
 9   host_total_listings_count    279547 non-null  float64
 10  host_has_profile_pic         279547 non-null  object
 11  host_identity_verified       279547 non-null  object
 12  neighbourhood                279712 non-null  object
 13  district                     37012 non-null   object
 14  city                         279712 non-null  object
 15  latitude                     279712 non-null  float64
 16  longitude                    279712 non-null  float64
 17  property_type                279712 non-null  object
 18  room_type                    279712 non-null  object
 19  accommodates                 279712 non-null  int64
 20  bedrooms                     250277 non-null  float64
 21  amenities                    279712 non-null  object
 22  price                        279712 non-null  int64
 23  minimum_nights               279712 non-null  int64
 24  maximum_nights               279712 non-null  int64
 25  review_scores_rating         188307 non-null  float64
 26  review_scores_accuracy       187999 non-null  float64
 27  review_scores_cleanliness    188047 non-null  float64
 28  review_scores_checkin        187941 non-null  float64
 29  review_scores_communication  188025 non-null  float64
 30  review_scores_location       187937 non-null  float64
 31  review_scores_value          187927 non-null  float64
 32  instant_bookable             279712 non-null  object
dtypes: float64(13), int64(6), object(14)
memory usage: 70.4+ MB

In [ ]:
listings.isna().sum() / len(listings) * 100

listing_id                      0.000000
name                            0.061849
host_id                         0.000000
host_since                      0.058989
host_location                   0.300309
host_response_time             46.040928
host_response_rate             46.040928
host_acceptance_rate           40.429799
host_is_superhost               0.058989
host_total_listings_count       0.058989
host_has_profile_pic            0.058989
host_identity_verified          0.058989
neighbourhood                   0.000000
district                       86.767818
city                            0.000000
latitude                        0.000000
longitude                       0.000000
property_type                   0.000000
room_type                       0.000000
accommodates                    0.000000
bedrooms                       10.523324
amenities                       0.000000
price                           0.000000
minimum_nights                  0.000000
maximum_nights                  0.000000
review_scores_rating           32.678255
review_scores_accuracy         32.788368
review_scores_cleanliness      32.771208
review_scores_checkin          32.809104
review_scores_communication    32.779073
review_scores_location         32.810534
review_scores_value            32.814109
instant_bookable                0.000000
dtype: float64

In [ ]:
listings.skew()

<ipython-input-24-568dc74f9e3b>:1: FutureWarning: The default value of numeric_only in DataFrame.skew is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  listings.skew()

listing_id                      -0.193098
host_id                          0.955389
host_response_rate              -2.268489
host_acceptance_rate            -1.863825
host_total_listings_count       23.490094
latitude                        -0.710930
longitude                        0.490553
accommodates                     2.197609
bedrooms                        13.213384
price                           61.616178
minimum_nights                 123.170870
maximum_nights                 284.220653
review_scores_rating            -3.758450
review_scores_accuracy          -4.213310
review_scores_cleanliness       -3.027859
review_scores_checkin           -5.262128
review_scores_communication     -5.230256
review_scores_location          -4.317991
review_scores_value             -3.253842
dtype: float64

In [ ]:
test_column = listings['amenities'][:5]
test_column = test_column.apply(eval)
pd.set_option('display.max_colwidth', None)
print(test_column)
test_column[0][2]

0                                                                    [Heating, Kitchen, Washer, Wifi, Long term stays allowed]
1                                        [Shampoo, Heating, Kitchen, Essentials, Washer, Dryer, Wifi, Long term stays allowed]
2                                                                [Heating, TV, Kitchen, Washer, Wifi, Long term stays allowed]
3                                                                        [Heating, TV, Kitchen, Wifi, Long term stays allowed]
4    [Heating, TV, Kitchen, Essentials, Hair dryer, Washer, Dryer, Bathtub, Wifi, Elevator, Long term stays allowed, Cable TV]
Name: amenities, dtype: object

'Washer'

In [ ]:
list_of_amenities = []

for sublist in test_column:
  for item in sublist:
    if item not in list_of_amenities:
      list_of_amenities.append(item)

['Heating', 'Long term stays allowed', 'Washer', 'Wifi', 'Shampoo', 'Kitchen', 'Essentials', 'Dryer', 'TV', 'Hair dryer', 'Bathtub', 'Elevator', 'Cable TV']

0                                                    [Heating, Long term stays allowed, Washer, Wifi, Long term stays allowed]
1                                        [Shampoo, Heating, Kitchen, Essentials, Washer, Dryer, Wifi, Long term stays allowed]
2                                                                [Heating, TV, Kitchen, Washer, Wifi, Long term stays allowed]
3                                                                        [Heating, TV, Kitchen, Wifi, Long term stays allowed]
4    [Heating, TV, Kitchen, Essentials, Hair dryer, Washer, Dryer, Bathtub, Wifi, Elevator, Long term stays allowed, Cable TV]
Name: amenities, dtype: object

In [ ]:
listings.columns

Index(['listing_id', 'name', 'host_id', 'host_since', 'host_location',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_total_listings_count',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'district', 'city', 'latitude', 'longitude', 'property_type',
       'room_type', 'accommodates', 'bedrooms', 'amenities', 'price',
       'minimum_nights', 'maximum_nights', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'instant_bookable'],
      dtype='object')

In [ ]:
from numpy import NaN
listings2 = listings.copy
listings2 = listings.drop(columns = ['listing_id', 'name', 'host_id', 'host_since', 'host_location',
       'host_response_time', 'host_response_rate', 'host_acceptance_rate',
       'host_is_superhost', 'host_total_listings_count',
       'host_has_profile_pic', 'host_identity_verified', 'neighbourhood',
       'district', 'city', 'latitude', 'longitude', 'property_type',
       'room_type', 'accommodates', 'bedrooms', 'price',
       'minimum_nights', 'maximum_nights', 'review_scores_rating',
       'review_scores_accuracy', 'review_scores_cleanliness',
       'review_scores_checkin', 'review_scores_communication',
       'review_scores_location', 'review_scores_value', 'instant_bookable'] )

for col in list_of_amenities:
  listings2[col] = NaN

for amenity in list_of_amenities:
  listings2[amenity] = listings2['amenities'].apply(lambda x: 1 if amenity in x else 0)

listings2

,amenities,Heating,Long term stays allowed,Washer,Wifi,Shampoo,Kitchen,Essentials,Dryer,TV,Hair dryer,Bathtub,Elevator,Cable TV
0,"[""Heating"", ""Kitchen"", ""Washer"", ""Wifi"", ""Long term stays allowed""]",1,1,1,1,0,1,0,0,0,0,0,0,0
1,"[""Shampoo"", ""Heating"", ""Kitchen"", ""Essentials"", ""Washer"", ""Dryer"", ""Wifi"", ""Long term stays allowed""]",1,1,1,1,1,1,1,1,0,0,0,0,0
2,"[""Heating"", ""TV"", ""Kitchen"", ""Washer"", ""Wifi"", ""Long term stays allowed""]",1,1,1,1,0,1,0,0,1,0,0,0,0
3,"[""Heating"", ""TV"", ""Kitchen"", ""Wifi"", ""Long term stays allowed""]",1,1,0,1,0,1,0,0,1,0,0,0,0
4,"[""Heating"", ""TV"", ""Kitchen"", ""Essentials"", ""Hair dryer"", ""Washer"", ""Dryer"", ""Bathtub"", ""Wifi"", ""Elevator"", ""Long term stays allowed"", ""Cable TV""]",1,1,1,1,0,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279707,"[""Iron"", ""Heating"", ""Washer"", ""Dedicated workspace"", ""Elevator"", ""Smoke alarm"", ""Wifi"", ""Kitchen"", ""Hot water"", ""Hangers"", ""Essentials"", ""TV""]",1,0,1,1,0,1,1,0,1,0,0,1,0
279708,"[""Shampoo"", ""Iron"", ""Heating"", ""Washer"", ""Hair dryer"", ""Elevator"", ""Wifi"", ""Kitchen"", ""Hot water"", ""Hangers"", ""Essentials"", ""TV""]",1,0,1,1,1,1,1,0,1,1,0,1,0
279709,"[""Paid parking off premises"", ""Shampoo"", ""First aid kit"", ""Heating"", ""Iron"", ""Kitchen"", ""Hair dryer"", ""Essentials"", ""Washer"", ""Breakfast"", ""Hot water"", ""Wifi"", ""Long term stays allowed"", ""Dedicated workspace"", ""Host greets you""]",1,1,1,1,1,1,1,0,0,1,0,0,0
279710,"[""TV"", ""Iron"", ""Kitchen"", ""Hangers"", ""Smoke alarm"", ""Cable TV"", ""Dedicated workspace"", ""Hot water"", ""Heating"", ""Shampoo"", ""Elevator"", ""Essentials"", ""Washer"", ""Carbon monoxide alarm"", ""Wifi""]",1,0,1,1,1,1,1,0,1,0,0,1,1
279711,"[""Shower gel"", ""Shampoo"", ""Iron"", ""Heating"", ""Washer"", ""Dedicated workspace"", ""Extra pillows and blankets"", ""Wifi"", ""Dishes and silverware"", ""Kitchen"", ""Refrigerator"", ""Cooking basics"", ""Hot water"", ""Essentials"", ""Bed linens"", ""Dishwasher"", ""Coffee maker""]",1,0,1,1,1,1,1,0,0,0,0,0,0

In [ ]:
listings.dtypes

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Mounted at /gdrive